default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: venture_development
  username: mysql
  password: 'root'
  host: localhost
